"""add creator_stake_pct and supply_model to cards

Revision ID: 13fa287fe2ff
Revises: 6c06932959d3
Create Date: 2026-09-11 08:41:35.771980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13fa287fe2ff'
down_revision: Union[str, Sequence[str], None] = '6c06932959d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'cards',
        sa.Column('creator_stake_pct', sa.Float(), nullable=False, server_default='0.0'),
    )
    op.add_column(
        'cards',
        sa.Column('supply_model', sa.String(), nullable=False, server_default='fixed'),
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'supply_model')
    op.drop_column('cards', 'creator_stake_pct')
    # ### end Alembic commands ###
