"""add price_history table

Revision ID: ba1d8bdd94f4
Revises: 13fa287fe2ff
Create Date: 2026-09-13 09:43:32.320946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1d8bdd94f4'
down_revision: Union[str, Sequence[str], None] = '13fa287fe2ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_card_id'), 'price_history', ['card_id'], unique=False)
    op.create_index(op.f('ix_price_history_created_at'), 'price_history', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_created_at'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_card_id'), table_name='price_history')
    op.drop_table('price_history')
    # ### end Alembic commands ###
